### ISSUE TITLE
"Pickup" / duo scenario option only showing Nordenwatch games instead of all maps in the Discordant Skirmish mode

### ISSUE THREAD

**Issue by Zomega-WAR** [dalen/killboard#230]
As of a week or two, the pickup/duo queue was replaced with the "Discordant Skirmish" queue which has an expanded map pool. However, picking the "Pickup" option on the killboard's scenario page only lists Nordenwatch rather than all of the Discordant Skirmish maps that have been played.

I do not know if it's missing the other games, or is just incorrectly listing every game as being played on the Nordenwatch map even if it actually took place in a different map.

https://killboard.returnofreckoning.com/scenarios?queue_type=duo

![image](https://user-images.githubusercontent.com/60266177/191135498-6a74ff85-b705-4538-9bec-d0700e24217c.png)

**Comment by dalen** [comment]
This has been fixed.
